Add get method for csv file, webhook handler
Antyfreezze/monefy-web-app pull request #1
Opened 2022-01-17 16:35 UTC by parseltonguedev

- get method for read csv file from dropbox
- write method to save csv files on instance
- dropbox webhook handler

2022-01-18 09:09 UTC, Antyfreezze requested changes

2022-01-18 09:09 UTC, Antyfreezze commented on utils.py
> +        with open(f'monefy_{time.strftime("%Y%m%d-%H%M%S")}.csv', 'wb') as f:
Maybe timestamp will be more precise here?

2022-01-18 09:09 UTC, Antyfreezze commented on utils.py
> +    return 'done'
This is very strange return value. If you need to understand the result of the execution it will be more convenient to use boolean values, or raise specific exceptions to send "bad" signal.

2022-01-18 09:09 UTC, Antyfreezze commented on utils.py
> +    file_names = [entry.name for entry in dbx.files_list_folder(FOLDER).entries
DRY

2022-02-02 10:43 UTC, Antyfreezze commented on run.py
> +@app.get("/healthcheck")
Due to consistency of code, I would like to see this endpoint with other endpoints.

2022-02-02 10:43 UTC, Antyfreezze commented on run.py
> +@click.option("--debug", default=True)
I suppose, all debug flags should be false. If developer need those to be enabled, he would use cmd line arguments to enable explicitly.

2022-02-02 10:43 UTC, Antyfreezze commented on src/domain/dropbox_lib.py
> +import os
I suppose this file doesn't implement dropbox's functionality only use it. So it will be more clear to name it something like 'dropbox_utils'

2022-02-02 10:43 UTC, Antyfreezze commented on src/domain/dropbox_lib.py
> +import os
Maybe  the better way is to create class DropboxClient, cause the only functionality I can see here is focused on contacting with Dropbox and store received data.
What do you think about such approach?

2022-02-02 10:43 UTC, Antyfreezze commented on src/resources/monefy_service.py
> +            return json({"message": False})
If there is no data was found, we should return 404 HTTP code with more explicit message than 'False'.

2022-02-02 10:43 UTC, Antyfreezze commented on src/resources/monefy_service.py
> +        return json({"success": write_result})
There is no need in 'success' field. To be consistent within all endpoint, it should be named 'message' and return data, with HTTP code 200. 200 code itself means that all is OK and request was successful.

2022-02-02 10:43 UTC, Antyfreezze commented on src/resources/monefy_service.py
> +    async def put(self, request):
I suppose this is redundant part, if we don't use those methods.

2022-02-02 10:43 UTC, Antyfreezze commented on src/resources/monefy_service.py
> +secret = os.environ.get("DROPBOX_APP_SECRET")
Correct me if I wrong, but nobody except DropboxWebHook need to know this info. Maybe we should move it into constants.py or into Hook class itself?

2022-02-02 10:43 UTC, Antyfreezze commented on src/resources/monefy_service.py
> +            return json({"message": False}, status=HTTPStatus.FORBIDDEN)
'False' is not the most convenient way to say that some kind of error happened. Maybe in such cases 'message' part may be omitted?

2022-02-02 10:43 UTC, Antyfreezze commented on src/resources/monefy_service.py
> +monefy_bp.add_route(MonefyInfo.as_view(), "/monefy_info")
I suppose this is not the best place for adding routes.

2022-02-11 21:08 UTC, parseltonguedev commented on src/resources/monefy_service.py
> +monefy_bp.add_route(MonefyInfo.as_view(), "/monefy_info")
moved to run.py

2022-02-11 21:09 UTC, parseltonguedev commented on src/resources/monefy_service.py
> +secret = os.environ.get("DROPBOX_APP_SECRET")
moved to ViewWithDropboxClient (HTTPMethodView child class)

2022-02-11 21:11 UTC, parseltonguedev commented on src/resources/monefy_service.py
> +            return json({"message": False}, status=HTTPStatus.FORBIDDEN)
changed to sanic raise exceptions

2022-02-11 21:11 UTC, parseltonguedev commented on src/resources/monefy_service.py
> +    async def put(self, request):
unused methods removed

2022-02-11 21:12 UTC, parseltonguedev commented on src/resources/monefy_service.py
> +        return json({"success": write_result})
renamed to "message", added HTTP code response

2022-02-11 21:13 UTC, parseltonguedev commented on src/resources/monefy_service.py
> +            return json({"message": False})
changed to sanic 404 exception

2022-02-11 21:14 UTC, parseltonguedev commented on src/domain/dropbox_lib.py
> +import os
file renamed to "dropbox_utils", DropboxClient class implemented

2022-02-11 21:14 UTC, parseltonguedev commented on run.py
> +@click.option("--debug", default=True)
changed default parameters status

2022-02-11 21:15 UTC, parseltonguedev commented on run.py
> +@app.get("/healthcheck")
added healthcheck endpoint to class based view

2022-02-16 08:27 UTC, Antyfreezze commented on src/resources/monefy_service.py
> +healthcheck_bp = Blueprint("healthcheck_bp")
Do we need this here? I can see blueprints within app file.

2022-02-16 08:31 UTC, Antyfreezze requested changes
Overall this iteration is much better than the previous one. I suppose there is a need to truncate commits, fix some points, after this will be done, we may merge this PR.

Great job!

2022-02-16 08:31 UTC, Antyfreezze commented on README.md
> +# monefy-web-app
We should leave 1 README file.

2022-09-02 11:12 UTC, closed without merging